import fs from "node:fs";
import path from "node:path";
import { generate } from "@babel/generator";
import * as t from "@babel/types";
import { glob } from "glob";

console.log("🚀 Generating index...");

const SOURCE_DIR = path.resolve(import.meta.dirname, "../src");
const INDEX_PATH = path.join(SOURCE_DIR, "index.ts");

async function generateIndex() {
	// Find all TS files except index.ts and files in excluded directories
	const files = await glob("**/*.ts", {
		cwd: SOURCE_DIR,
		ignore: ["index.ts", "**/*.d.ts", "**/__tests__/**", "**/__mocks__/**", "**/internal/**", "**/private/**"],
	});

	// Create the array of exports and sort it
	const exports = files
		.map((file) => {
			const imp = file.replaceAll("\\", "/").replace(/\.ts$/, "");
			return `@/${imp}`;
		})
		.sort();

	// Create the AST tree
	const exportNodes = exports.map((exp) => t.exportAllDeclaration(t.stringLiteral(exp)));

	// Create the program with exports
	const program = t.program(exportNodes);

	// Generate code from the AST
	const { code } = generate(program as any);

	// Build the final file contents
	const content = `// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is automatically created by scripts/generate:index.ts.
// Use 'npm run generate:index' to regenerate.
/** biome-ignore-all assist/source/organizeImports: <AUTO-GENERATED> */

${code}
`;

	// Write to the file
	fs.writeFileSync(INDEX_PATH, content, "utf-8");
	console.log(`✅ Generated ${INDEX_PATH} with ${exports.length} exports`);
}

generateIndex().catch(console.error);
